create extension if not exists pgcrypto;

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text not null,
  business_type text,
  revenue text,
  message text
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);

create table if not exists public.settings (
  id bigint primary key generated by default as identity,
  admin_email text not null
);

insert into public.settings (id, admin_email)
values (1, 'admin@example.com')
on conflict (id) do nothing;

alter table public.leads enable row level security;
alter table public.settings enable row level security;

drop policy if exists "authenticated can read leads" on public.leads;
create policy "authenticated can read leads"
on public.leads
for select
to authenticated
using (true);

drop policy if exists "authenticated can read settings" on public.settings;
create policy "authenticated can read settings"
on public.settings
for select
to authenticated
using (true);

drop policy if exists "authenticated can update settings" on public.settings;
create policy "authenticated can update settings"
on public.settings
for update
to authenticated
using (true)
with check (true);

grant select on public.leads to authenticated;
grant select, update on public.settings to authenticated;
